# Practical_6: Numpy

In [6]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [9]:
# Exercise 1
f_array = np.arange(1, 11)
f_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [16]:
# Exercise 2
s_array = np.zeros((3, 3))
s_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [19]:
# Exercise 3
T_array = np.linspace(0, 5, 10)
T_array 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [22]:
# Exercise 4
fo_array  = np.eye(5)
fo_array 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [25]:
# Exercise 5
fi_array = np.random.rand(4, 4)
fi_array


array([[0.2393427 , 0.97646408, 0.33147967, 0.90240665],
       [0.29559246, 0.57780586, 0.93671353, 0.25769445],
       [0.51905703, 0.93509244, 0.10467275, 0.74637255],
       [0.65750538, 0.42004901, 0.03829345, 0.12431183]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [28]:
# Exercise 6
array_shape =fo_array .shape
array_shape


(5, 5)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [31]:
# Exercise 7
id_array = np.arange(16).reshape(4, 4)
id_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [34]:
# Exercise 8
data_type = fo_array.dtype
data_type

dtype('float64')


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [37]:
# Exercise 9
num_array = np.arange(1,100)
even = num_array[num_array% 2 ==0]
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [40]:
# Exercise 10
array_10 = np.random.randint(10, 51, (6, 6))
array_10

array([[44, 41, 12, 17, 16, 20],
       [28, 18, 16, 17, 30, 35],
       [49, 16, 46, 45, 24, 26],
       [24, 45, 28, 20, 34, 21],
       [14, 15, 35, 15, 41, 48],
       [10, 46, 49, 26, 14, 15]])


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [43]:
# Exercise 11
sub_matrix =array_10[1:4, 2:5]
sub_matrix

array([[16, 17, 30],
       [46, 45, 24],
       [28, 20, 34]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [46]:
# Exercise 12
sum_9 = num_array.sum()
sum_9

4950


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [49]:
# Exercise 13
mean =np.mean (array_10)
median = np.median(array_10)
std = np.std(array_10)
std

12.592129621118968


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [52]:
# Exercise 14
max_14 = num_array.max()
min_14 = num_array.min()
print(min_14, max_14)

1 99



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [55]:
# Exercise 15
num_15 = np.random.randint(0, 200, 20)
max_index15 = np.argmax(num_15)
max_index15 

3


---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [58]:
# Exercise 16
array_16 = np.arange(1,19)[::-1]
array_16

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
        1])


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [61]:
# Exercise 17
matrix_1 = np.random.randint(1,20,(3,3))
matrix_2 = np.random.randint(1,40,(3,3))
elemnt_wse = matrix_1*matrix_2
elemnt_wse

array([[209, 247,  45],
       [368, 104,  32],
       [456,  33, 480]])


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [64]:
# Exercise 18
array_18 = np.array([1, 2, 3, 4,5])
diag_18 = np.diag(array_18)
diag_18

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [67]:
# Exercise 19
matrx_3 = np.array([[1, 4], [2, 4]])
matrx4 = np.array([[8, 6], [10, 8]])
product = np.dot(matrx_3, matrx_4)
product

NameError: name 'matrx_4' is not defined


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [ ]:
# Exercise 20
flat_array = matrx_4.flatten()
flat_array


---

### Exercise 21:
Stack two NumPy arrays vertically.


In [71]:
# Exercise 21
array_1 = np.array([[1, 5], [3, 9]])
array_2 = np.array([[5, 11]])
stacked_v = np.vstack((array_1, array_2))
stacked_v

array([[ 1,  5],
       [ 3,  9],
       [ 5, 11]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [74]:
# Exercise 22
stacked_h = np.hstack((array_1, array_2.T))
stacked_h

array([[ 1,  5,  5],
       [ 3,  9, 11]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [144]:
# Exercise 23
array_23 = np.arange(16)
split_23 = np.split(array_23, 4)
split_23

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [156]:
# Exercise 24
array_24 = np.random.rand(3, 3)
round_24 = np.round(array_24, 2)
round_24


array([[0.98, 0.36, 0.36],
       [0.48, 0.38, 0.55],
       [0.25, 0.57, 0.04]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [158]:
# Exercise 25
array_25 = np.array([3, 2, 4, 2, 4, 4])
unique_ele = np.unique(array_25)
unique_ele

array([2, 3, 4])


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [162]:
# Exercise 26
array_26 = np.array([1, 6, 3, 2, 8])
array_26[array_26 < 4] = 4
array_26

array([4, 6, 4, 4, 8])


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [164]:
# Exercise 27
array_27 = np.array([1, 2, 10])
cum_sum = np.cumsum(array_27)
cum_sum

array([ 1,  3, 13])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [170]:
# Exercise 28
array_28 = np.array([0, 0, 0, 2, 4 , 0])
nonzero_ele = np.count_nonzero(array_28)
nonzero_ele

2


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [172]:
# Exercise 29
array_29 = np.random.randint(0, 200, 10)
sorted_int = np.sort(array_29)
sorted_int

array([ 10,  24,  81,  94, 147, 153, 172, 174, 175, 199])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [174]:
# Exercise 30
matrx_30 = np.random.randint(1, 20, (3, 3))
row_sum30 = mat30.sum(axis=1)
col_sum30 = mat30.sum(axis=0)
print(row_sum30, col_sum30)

[ 8  9 26] [13 15 15]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [136]:
# Exercise 31
array_31 = np.random.rand(3, 3)
norm_31 = (array_31 - array_31.min()) / (array_31.max() - array_31.min())
norm_31

array([[0.6827286 , 0.47661662, 0.        ],
       [0.78729434, 1.        , 0.47747913],
       [0.77028222, 0.87336041, 0.93302643]])


---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [134]:
# Exercise 32
st_32 = np.array([2, 2])
nd_32 = np.array([3, 4])
dot_32 = np.dot(st_32, nd_32)
dot_32

14


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [176]:
# Exercise 33
matrx_33 = np.array([[1, 2], [6, 4]])
trace = np.trace(matrx_33)
trace

5


---

### Exercise 34:
Create a 2D array and swap two rows.


In [128]:
# Exercise 34
matrx_34 = np.array([[2, 4], [3, 4]])
matrx_34[[0, 1]] = matrx_34[[1, 0]]
matrx_34

array([[3, 4],
       [2, 4]])


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [126]:
# Exercise 35
array_35 = np.array([3, 4, 5])
column_35 = array_35[:, np.newaxis]
column_35

array([[3],
       [4],
       [5]])


---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [122]:
# Exercise 36
matrx_36 = np.array([[2, 2, 4], [0, 3, 4], [5, 6, 0]])
determinant_36 = np.linalg.det(matrx_36)
determinant_36

-68.00000000000001


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [118]:
# Exercise 37
matrx_37 = np.array([[8, -2], [2, 1]])
eigvalues_37, eigvectors_s37 = np.linalg.eig(matrx_37)
print(eigvalues_37, eigvectors_s37)

[7.37228132 1.62771868] [[0.95411001 0.29945634]
 [0.29945634 0.95411001]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [ ]:
# Exercise 38
#Solve: 2x + 2y = 8, 2x + 4y = 10
A_38 = np.array([[2, 2], [2, 4]])
b_38 = np.array([8, 10])
solution_ = np.linalg.solve(A_38, b_38)
solution_


---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [ ]:
# Exercise 39
array_39 = np.array([2, 2, 3])
noise_39 = np.random.normal(0, 1, array_39.shape)
noisy_array_39 = array_39 + noise_39
noisy_array_39


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [ ]:
# Exercise 40
matrx_40 = np.random.randint(1, 12, (5, 5))
diag_40 = np.diag(matrx_40)
diag_40


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [ ]:
# Exercise 41
array_41 = np.random.rand(100) * 100
clip_41 = np.clip(arr41, 10, 50)
clipp_41


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [ ]:
# Exercise 42
array_42 = np.array([[1, -3], [-5, 10]])
array_42[array_42 < 0] = 0
array_42


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [221]:
# Exercise 43
x_43 = np.array([2, 3])
y_43 = np.array([4, 5])
inner_43 = np.inner(x_43, y_43)
outer_43 = np.outer(x_43, y_43)
print(outer_43, inner_43)

[[ 8 10]
 [12 15]] 23



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [219]:
# Exercise 44
points_44 = np.random.rand(6, 4)
from scipy.spatial.distance import pdist, squareform
pairwise_dist_44 = squareform(pdist(points_44 ))
pairwise_dist_44 

array([[0.        , 1.14791753, 0.69531905, 0.38303061, 0.79854407,
        0.70028963],
       [1.14791753, 0.        , 0.59816111, 1.23161401, 1.07007366,
        0.61640058],
       [0.69531905, 0.59816111, 0.        , 0.70748124, 0.60460463,
        0.35167791],
       [0.38303061, 1.23161401, 0.70748124, 0.        , 0.81355768,
        0.87388953],
       [0.79854407, 1.07007366, 0.60460463, 0.81355768, 0.        ,
        0.59594855],
       [0.70028963, 0.61640058, 0.35167791, 0.87388953, 0.59594855,
        0.        ]])


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [211]:
# Exercise 45
array_45 = np.array([('Winnie', 35, 1.75), ('David', 26, 1.80)],
                 dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
array_45

array([('Winnie', 35, 1.75), ('David', 26, 1.8 )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f4')])


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [203]:
# Exercise 46
matrx_46 = np.random.randint(0, 10, (5, 5))
unique_vals_46, counts_46 = np.unique(matrx_46, return_counts=True)
counts_46

array([5, 5, 2, 1, 1, 2, 2, 6, 1], dtype=int64)


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [199]:
# Exercise 47
matrx_47 = np.random.rand(3, 3)
mean_row_47 = matrx_47.mean(axis=1, keepdims=True)
centered_47 = matrx_47 - mean_row_47
centered_47

array([[ 0.20735903,  0.2926186 , -0.49997763],
       [-0.13617748, -0.32680639,  0.46298388],
       [-0.01522347,  0.13474895, -0.11952548]])


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [197]:
# Exercise 48
array_48 = np.random.randint(0, 99, 10)
greater_50 = np.any(array_48 > 50)
greater_50

True


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [195]:
# Exercise 49
ID_array = np.random.rand(12)
window = 3
moving_average = np.convolve(ID_array, np.ones(window)/window, mode='valid')
moving_average

array([0.35366946, 0.47015118, 0.47173702, 0.56398967, 0.48540269,
       0.59001506, 0.52187627, 0.65350071, 0.57397589, 0.52475253])


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [191]:
# Exercise 50
array_x_50 = np.random.rand(10)
array_y_50 = np.random.rand(10)
correlation_50 = np.corrcoef(array_x_50,array_y_50)[0, 1]
correlation_50

0.18695958911784938


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [183]:
# Exercise 51
rad_51 = np.array([0, np.pi/2, np.pi])
degree_51 = np.degrees(rad_51)
degree_51

array([  0.,  90., 180.])


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [177]:
# Exercise 52
array_52 = np.random.rand(12)
variance_52 = np.var(array_52)
std_52 = np.std(array_52)
print(variance_52, std_52)

0.06499583333748964 0.2549428040512021



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [171]:
# Exercise 53
array_53 = np.random.rand(3, 3)
max_idx_row53 = np.argmax(array_53, axis=1)
max_idx_col53 = np.argmax(array_53, axis=0)
print(max_idx_row53, max_idx_col53)

[0 1 2] [0 1 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [145]:
# Exercise 54
matrx_54 = np.array([[4, 8], [10, 12]])
inverse_54 = np.linalg.inv(matrx_54)
inverse_54

array([[-0.375 ,  0.25  ],
       [ 0.3125, -0.125 ]])


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [143]:
# Exercise 55
array_55 = np.random.rand(10)
standardize_55 = (array_55 - np.mean(array_55)) / np.std(array_55)
standardize_55

array([-1.27765206, -0.86321401,  0.51157337,  1.15009925, -0.25216706,
       -0.8571852 , -0.52356926,  1.17301349, -0.78516742,  1.72426889])


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [139]:
# Exercise 56
a_56 = np.array([4, 6, 8])
b_56 = np.array([10, 12, 14])
add56 = a_56 + b_56
sub56 = a_56 - b_56
print(add56, sub56)

[14 18 22] [-6 -6 -6]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [133]:
# Exercise 57
array_57 = np.random.rand(12)
max_index57 = np.argmax(array_57)
max_index57

11


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [131]:
# Exercise 58
array_58 = np.arange(9).reshape(3, 3)
rotate_58 = np.rot90(array_58)
rotate_58

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [113]:
# Exercise 59
matrx_59 = np.array([[1, 4], [8, 4]])
frobenius_59 = np.linalg.norm(matrx_59)
frobenius_59

9.848857801796104


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [111]:
# Exercise 60
array_60 = np.arange(27).reshape(3, 3, 3)
sub_array60 = array_60[1:, :, 1:]
sub_array60

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])


---